### ISSUE TITLE
IFS->Announcement Feature

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#139]
This feature would be different than class announcement but would be news created by an admin.
Announcements could be until viewed, or specific timeline.

**Comment by kglovern** [comment]
Are course announcements a feature yet?  If not, probably a good idea to make this usable for both - not much will change between the two besides instructors being limited to the scope of courses they have ownership over.

_As an admin, I want to make or edit a news announcement that is visible to all users of the system, so that they are aware of upcoming system changes or downtime_
- Log in to admin panel announcement creation page
- Given option to create/update title and text body
- Given option to set expiry date

_As an instructor, I want to make or edit a news announcement that is visible to all students enrolled in my course, so that I can inform them of upcoming events or assignments_
- Login in to instructor panel announcement creation page
- Given option to select class(es) I am instructor for
- Given option to create/update title and text body
- Given option to set expiry date

_As a student, I want to view all news announcements related to the system and classes I am enrolled in, so that I can keep on top of my work load_
- View dashboard and see a list of all relevant announcements sorted by date created
- View separate announcements route and see all relevant announcements sorted by date

_As a student I want to be notified when announcements relevant to my interests have been created in the system_
- Visible component on the UI that highlights when a new announcement for the system/one of my courses has been posted
- Able to click on specific announcement to view full text
- Email notification as an opt-in feature

_As a student, I want to be able to mute announcements from a particular course I am enrolled in_

**Comment by kglovern** [comment]
Feature pull request: https://github.com/ian-james/IFS/pull/154

**Comment by GrantDouglas** [comment]
Merged and working!
