### ISSUE TITLE
Upload-> Save all student submissions.

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#151]
The code was previously available in GitHub might need slight modifications to be integrated into updated codebase.

However, this should be made available via a bool on/off option. Since this needs an amendment from the Ethical document currently being written.

**Comment by ryoung2512** [comment]
We already discussed this, just updating it here. So that anyone who works on it knows what we currently have.

As it currently stands, we are saving ALL submissions. The folder structure is users/id/timestamp. In order for us to really delete submissions, we should probably make the feedback page work off the database. One issue with this, however, is that the feedback references lines in a file. If we are not storing the files it will be a little weird to provide feedback.

Need to make some design decisions based off ethics.

**Comment by ian-james** [comment]
It's ok not to have the previous files and the information is still useful.
The idea would be more for post analysis that we could determine if students had fixed the bug they viewed or not. Clustering errors or many more of those types of comparisons that don't need the original content can still be done.

**Comment by GrantDouglas** [comment]
Looks like Rhys finished this.
