### ISSUE TITLE
Update Tool Descriptions

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#23]
See comments on commits https://github.com/ian-james/IFS/commit/253a4f1b25925381fa7ed1fd47043b47606095df and https://github.com/ian-james/IFS/commit/1649e3d4bb68e11170f4a5265097738910bb952e; from here on out, tools should have descriptions in their JSON entries in the toolLists, in order to populate the About page properly.

See commit 0c2c787 for details.

**Comment by ian-james** [comment]
Alright, I've added a short description to the tools attached to my named.
Also attached a couple license fields in JSON.

Small issue we can change later but tool display names might need to change to something like GCC Diagnostics, otherwise, it looks like I'm taking credit for writing GCC :)

BTW, we should add Judi and Dan to the contributors' list.
