### ISSUE TITLE
[Job Queue] Feedback processing chokes on large JSON output

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#30]
When testing `tests/testFiles/IFS_Test2_IPSUM.txt` with the spell check tool via the web interface, no feedback is given and no errors are shown.

However, running the following spits out a huge JSON object:
```bash
tools/languageTools/spell_check/spell_check.py -l en_US -i tests/testFiles/IFS_Test2_IPSUM.txt 
```
Is IFS choking on large JSON files?

**Comment by ian-james** [comment]
The potential is there for that to occur, I'll have to look into this is more detail  but the way that jobs are handled might have to change to better manage large streams of data, rather than a single chunk. 

The problem related to the Node JS function exec vs spawn.
Just found this looks like a super quick intro.
https://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html

Not passing the buck on this, so just in case your interested in how the job queue works, the child job creates a child process using exec for each tool, which likely has to change to spawn and receive event emits. That way it can handle more data but just has to be more careful with handling state inforamation.

**Comment by ian-james** [comment]
Hopefully, this is fixed....got 750+ errors from spell checker for ipsum2.
No issues....well other taking quite a while to process

**Comment by keeferrourke** [comment]
Are we okay to close this for now? It hasn't crashed in any of my testing. The only that I haven't tested is having simultaneous uploads and processing from multiple users. Not really sure how to test that case unless we get a bunch of people registered on and logged into the SOCS server instance.

**Comment by ian-james** [comment]
Closing based on hardware improvements which likely have to be the next couple resolutions to this problem.
