### ISSUE TITLE
[Feedback] Add Writing statistics summary

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#38]
Statistics that come to mind for any given english-type file, are:
 * number of words
 * number of sentences
 * number of errors
 * number of correctly-spelled words (?)
 * the most frequently used words (perhaps not necessary, as this is handled by wordcloud)

Number of words, sentences, and errors are already found by IFS, so should be easy to display.

**Comment by ian-james** [comment]
We might want to pair this task with investigating readability scores.
Since I'm assuming that some of those tools will need to accomplish the same tasks.

**Comment by ian-james** [comment]
Several of the writing stats are now available via feedback stats. Note a number of statistics are technically available but are not displayed in the UI. Stats that are calculated but not displayed are readability scores, since many of the scores range from elementary schools to college it might insulting/demotivating to receive low readability scores.

Cloc might be an easy tool to get setup and integrated. I'm going to leave statistics for the moment. 

Ideally, I would like to learn more about what the user changed from submission to submission so the more granular we can evaluate that the better so that we can link it to previously viewed feedback.

**Comment by ian-james** [comment]
Separating this task into two parts, so that this part can be closed.
Writing Task is closed, programming has a new issue.
