### ISSUE TITLE
Feedback Card contains Encoding Characters

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#4]
The horizontal tab &#x9 will show up on the mini-card feedback.

Other characters appear to be reconverted (decoded) properly.

**Comment by keeferrourke** [comment]
I found the source of this bug. It should have been obvious to me before, but that's life.

The horizontal tab character `&#x9;` is decoded properly everywhere, except where a line is highlighted for feedback. This is because the button link is inserted in the middle of the character encoding sequence, such as:
```html
&#<a href="">...</a>9;
```
This creates an HTML syntax error, which is why the DOM is not parsed properly. I'm going to mess around a bit, but am not totally sure where this injection happens in the codebase. Will report back if I find anything.

Screenshot:
![screenshot from 2017-05-24 14-31-01](https://cloud.githubusercontent.com/assets/6888381/26419507/f603d66e-408d-11e7-97a4-701cd21e0868.png)

**Comment by ian-james** [comment]
Take a look Tonight createButton method. It's in a file by itself. It is
injected during feedback setup

**Comment by keeferrourke** [comment]
I found the file, but I think the issue is that in FeedbackHighlighter.js, the offset:
```javascript
                offset += ( (str.length  - newStr.mid.length + 1 ) + contentObj.offset);
```
is being computed as if `&#x9;` is a single character, which, when encoded, it is not.

I might be wrong though...

**Comment by ian-james** [comment]
You could be right though! There is the potential for offset error because
of the encoding/decoding process occur after the tools.

**Comment by keeferrourke** [comment]
I think I have fixed all the encoding character problems. Commit coming soon.

**Comment by ian-james** [comment]
Reopening.
This fix causes a different issue that characters go missing from highlight section. I'll try to post screen later but the test cases with array.h will demonstrate that < and > symbols can disappear from the highlighted comments.

**Comment by keeferrourke** [comment]
I can't seem to be able to reproduce this issue?

**Comment by ian-james** [comment]
![feedback test page](https://cloud.githubusercontent.com/assets/4433774/26563650/16742b60-44a3-11e7-9aec-8e5b324f5fe0.png)

Try /tests/programmingTests/TestingExample.zip

In array.c should have a for loop with missing middle statement

**Comment by keeferrourke** [comment]
This isn't an issue with the syntax highlighting, but rather character encoding.

The original line in the C source is
```c
// Prints an integer array.
for( int i = 0; i<array->size; i++)
```

Specifically, then `<array->` sequence of characters looks a lot like a opening html tag for a non-existent `array-` block.

The page source looks like the following:
```html
&#x9;// Prints an integer array.
<a data-feedback='0' data-html="true" popover-trigger="'outsideClick'" ng-click="setSelectedItem( $event )" uib-popover-template="'components/Feedback/popoverMini.html'" popover-animation="true" popover-placement="bottom" class=" btnText nocode error ">	for( int i = 0; i<array->size; i++)</a>
&#x9;{
&#x9;&#x9;printf(&#x22;%d &#x22;, array-&#x3E;arr[i] );
&#x9;}
```

You should be able to see that the angle brackets are not encoded as HTML entities! This is a potential security risk, because it's a vector by which a clever attacker might be able to inject scripts.

The character encoding is done by `he.encode()` correct? This might be a problem with their upstream, that we have patch downstream.

**Comment by keeferrourke** [comment]
![image](https://cloud.githubusercontent.com/assets/6888381/26564260/c06bb71a-44ac-11e7-8463-9fb69fc1b281.png)
Using the old highlighting method, you can see that the error is still present.

**Comment by keeferrourke** [comment]
It seems like the targets need to be re-encoded once they have been wrapped by the <a></a> tags, though I am really unsure as to why they are decoded in the first place.

**Comment by keeferrourke** [comment]
This should be fixed now. The correct errors seem to be highlighted and associated with the correct feedback now as well.
