### ISSUE TITLE
Diction Tool

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#72]
Older Linux Text Tools
 (Diction, style and formulas
  Evaluate are they usable and different?
https://www.linux.com/news/improve-your-writing-gnu-style-checkers

**Comment by keeferrourke** [comment]
As noted during the meeting this morning, the diction tool seems to pick up on a lot of false positives. I'm inclined to leave it though because, I have affinity for its humour :grin:

> "Desert" and "dessert" are sometimes confused, to the delight of the masses.

Adding a description for this tool such as, "This tool checks for and highlights commonly misused words," might be a good idea to make sure the user is aware that the tool flags words which may not actually be errors.

**Comment by keeferrourke** [comment]
I think this can be closed, as I am not sure why this issue exists. I have added user-friendly descriptions to every tool in the IFS. In addition:

 * `diction` is used to find commonly misused words in phrases; the behaviour of the (recently renamed) IFS tool 'Word Use Checker' matches this
* `style` appears to be used to generate the writing statistics for the IFS

So to answer the question:

> Evaluate are they usable and different?

I would say yes, and they have been effectively incorporated into the system from my testing.

**Comment by ian-james** [comment]
Alright, I think so too. I wasn't sure if you wanted to or had added the these aren't necessary errors comment somewhere .
