### ISSUE TITLE
[Feature Request] Adding compiling flags

### ISSUE THREAD

**Issue by iam4722202468** [ian-james/IFS#85]
### Description
Add ability for user to add flags for the compiler to compile with, such as -lm

### Implementation
Add widget:
Upload > Programming Tool Screen > Additional compilation flags

Inside widget have a search bar where users can look up libraries and flags to add
Display active and inactive flags below search bar, with checkbox (to enable/disable) and delete button (to delete)
Store flags on a user basis, and for each upload get user flags and display them in this section

**Comment by keeferrourke** [comment]
This is going to be low-priority, since there are a number of critical features and fixes that need to be implemented. However, I'll make a mock-up UI as soon as I get chance. I think this would consist of a text-input and a method to display popular flags and select them.

I think the best way to make this work given the current underlying architecture is to:

 1. make a new `compilation_flags` database
 2. add a text-input field to relevant core-tools in the UI; this can allow users to enter a space delimited list of flags, such as `-DX_OPENSOURCE -lm -lncurses`, which would be stored in the database as:

| id | flag | times_used |
| --- | --- | --- |
| 1 | -DX_OPENSOURCE | 1 |
| 2 | -lm | 1 |
| 3 | -lncurses | 1|

 If a flag hasn't been used, it will be added to the database, if it is in the database, then the value in the times_used column should be incremented.

If a flag has been used X number of times, then it should be shown as a suggested flag in the UI, below the text-input. Clicking on the suggestion will automatically append the flag to the input field.

When the tool form is submitted, the list of flags should be passed to the [programmingParser](https://github.com/ian-james/IFS/blob/master/ifs/tools/programmingTools/c_tools/programmingParser.py). This will allow error suppression for undefined constants and errors caused by unlinked libraries.

**Comment by keeferrourke** [comment]
Things to investigate here:
  * detecting dangerous or invalid flags
  * if this input method can be used in any sort of harmful fashion

**Comment by iam4722202468** [comment]
> Things to investigate here:

>    detecting dangerous or invalid flags
>    if this input method can be used in any sort of harmful fashion

This could be solved by white listing flags and only having whitelisted flags appear in search bar

**Comment by keeferrourke** [comment]
I don't think a white-list of flags is a good idea. Or, at least it isn't the full solution. Sometimes defining arbitrary constants at compile time is important, such as if one is writing a library that can have optional functionality toggled by preprocessor definitions. The `-D` flag should be allowed to take any string, such as `-DMYSUPERCOOLFUNCTIONALITY`.

If there are dangerous flags that exist, perhaps they could be blacklisted instead.

**Comment by ian-james** [comment]
I believe the original IFS had a text box that allowed users to input flags as needed, although not sure what error checking was done beyond that. This is a good catch we will likely need to include access to some libraries, for CIS2520 ncurses and math come to mind but could be several others may need to be available.

**Comment by keeferrourke** [comment]
> @ian-james moved this from Unassigned to Done! :D in IFS on Sep 4, 2017

I assume this is closable?

**Comment by ian-james** [comment]
haha, definitely.
